require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RealestatesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Realestate. As you add validations to Realestate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RealestatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all realestates as @realestates" do
      realestate = Realestate.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:realestates)).to eq([realestate])
    end
  end

  describe "GET show" do
    it "assigns the requested realestate as @realestate" do
      realestate = Realestate.create! valid_attributes
      get :show, {:id => realestate.to_param}, valid_session
      expect(assigns(:realestate)).to eq(realestate)
    end
  end

  describe "GET new" do
    it "assigns a new realestate as @realestate" do
      get :new, {}, valid_session
      expect(assigns(:realestate)).to be_a_new(Realestate)
    end
  end

  describe "GET edit" do
    it "assigns the requested realestate as @realestate" do
      realestate = Realestate.create! valid_attributes
      get :edit, {:id => realestate.to_param}, valid_session
      expect(assigns(:realestate)).to eq(realestate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Realestate" do
        expect {
          post :create, {:realestate => valid_attributes}, valid_session
        }.to change(Realestate, :count).by(1)
      end

      it "assigns a newly created realestate as @realestate" do
        post :create, {:realestate => valid_attributes}, valid_session
        expect(assigns(:realestate)).to be_a(Realestate)
        expect(assigns(:realestate)).to be_persisted
      end

      it "redirects to the created realestate" do
        post :create, {:realestate => valid_attributes}, valid_session
        expect(response).to redirect_to(Realestate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved realestate as @realestate" do
        post :create, {:realestate => invalid_attributes}, valid_session
        expect(assigns(:realestate)).to be_a_new(Realestate)
      end

      it "re-renders the 'new' template" do
        post :create, {:realestate => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested realestate" do
        realestate = Realestate.create! valid_attributes
        put :update, {:id => realestate.to_param, :realestate => new_attributes}, valid_session
        realestate.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested realestate as @realestate" do
        realestate = Realestate.create! valid_attributes
        put :update, {:id => realestate.to_param, :realestate => valid_attributes}, valid_session
        expect(assigns(:realestate)).to eq(realestate)
      end

      it "redirects to the realestate" do
        realestate = Realestate.create! valid_attributes
        put :update, {:id => realestate.to_param, :realestate => valid_attributes}, valid_session
        expect(response).to redirect_to(realestate)
      end
    end

    describe "with invalid params" do
      it "assigns the realestate as @realestate" do
        realestate = Realestate.create! valid_attributes
        put :update, {:id => realestate.to_param, :realestate => invalid_attributes}, valid_session
        expect(assigns(:realestate)).to eq(realestate)
      end

      it "re-renders the 'edit' template" do
        realestate = Realestate.create! valid_attributes
        put :update, {:id => realestate.to_param, :realestate => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested realestate" do
      realestate = Realestate.create! valid_attributes
      expect {
        delete :destroy, {:id => realestate.to_param}, valid_session
      }.to change(Realestate, :count).by(-1)
    end

    it "redirects to the realestates list" do
      realestate = Realestate.create! valid_attributes
      delete :destroy, {:id => realestate.to_param}, valid_session
      expect(response).to redirect_to(realestates_url)
    end
  end

end
